[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions"

[dev]
  framework = "#auto"
  targetPort = 5173
  port = 8888
  edge_functions_port = 9999

[[edge_functions]]
  function = "api"
  path = "/.netlify/edge-functions/api"

[[redirects]]
  from = "/.netlify/edge-functions/api"
  to = "/.netlify/edge-functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"