[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[dev]
  command = "npm run dev" # 本地开发命令
  targetPort = 5173 # Vite 默认端口
  port = 8888 # Netlify Dev 端口
  publish = "dist"
  framework = "#custom"
  envFiles = [".env.local"] # 指定环境变量文件

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

# API 路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/edge-functions/api/:splat"
  status = 200

# SPA 回退路由 - 放在最后
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200